export default function TermsOfService() {
  const lastUpdated = "January 22, 2026";

  return (
    <div className="min-h-screen bg-black text-zinc-300 py-20 px-6">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-5xl font-black text-white italic uppercase tracking-tighter mb-4">
          Terms of Service
        </h1>
        <p className="text-zinc-500 text-sm mb-12">Last Updated: {lastUpdated}</p>

        <div className="space-y-12">
          {/* Section 1 */}
          <section>
            <h2 className="text-xl font-bold text-white uppercase tracking-widest mb-4 border-l-4 border-red-600 pl-4">
              1. Acceptance of Terms
            </h2>
            <p>
              By accessing BossWrite (&quot;the Service&quot;), you agree to be bound by these Terms. 
              If you are using the Service on behalf of a business, that business accepts these terms. 
              The Service is operated by [Your Registered Business Name], India.
            </p>
          </section>

          {/* Section 2 - FIXED: Changed <p> to <div> to allow <ul> inside */}
          <section>
            <h2 className="text-xl font-bold text-white uppercase tracking-widest mb-4 border-l-4 border-red-600 pl-4">
              2. Service Description & AI Credits
            </h2>
            <div className="space-y-2">
              <p>
                BossWrite provides AI-powered content generation using YouTube transcripts. 
                Access to features is governed by a &quot;Credits&quot; system. 
              </p>
              <ul className="list-disc ml-6 mt-2 space-y-2 text-zinc-400">
                <li>Credits are consumed upon successful transcription and post generation.</li>
                <li>Credits have no monetary value and are non-transferable.</li>
                <li>We reserve the right to limit video duration (currently 45 minutes) to ensure service stability.</li>
              </ul>
            </div>
          </section>

          {/* Section 3 - FIXED: Changed <p> to <div> */}
          <section>
            <h2 className="text-xl font-bold text-white uppercase tracking-widest mb-4 border-l-4 border-red-600 pl-4">
              3. YouTube & Third-Party Content
            </h2>
            <div className="space-y-2">
              <p>Our Service utilizes publicly available YouTube data. You agree that:</p>
              <ul className="list-disc ml-6 mt-2 space-y-2 text-zinc-400">
                <li>You will only use the Service for videos you have the right to access.</li>
                <li>You will comply with YouTube&apos;s Terms of Service.</li>
                <li>BossWrite is not affiliated with or endorsed by YouTube or Google.</li>
              </ul>
            </div>
          </section>

          {/* Section 4 */}
          <section>
            <h2 className="text-xl font-bold text-white uppercase tracking-widest mb-4 border-l-4 border-red-600 pl-4">
              4. User Content & AI Output
            </h2>
            <p>
              You own the &quot;Manifestos&quot; generated by our AI. However, due to the nature of machine learning, 
              outputs may not be unique across users. You are responsible for reviewing and 
              fact-checking any content before publishing it to social media.
            </p>
          </section>

          {/* Section 5 */}
          <section>
            <h2 className="text-xl font-bold text-white uppercase tracking-widest mb-4 border-l-4 border-red-600 pl-4">
              5. Payments & Refunds
            </h2>
            <p>
              Payments are processed via Cashfree/Stripe. By purchasing credits, you agree to their 
              respective terms. As per our <strong>Refund Policy</strong>, digital credits are 
              non-refundable once consumed or assigned to your account.
            </p>
          </section>

          {/* Section 6 */}
          <section>
            <h2 className="text-xl font-bold text-white uppercase tracking-widest mb-4 border-l-4 border-red-600 pl-4">
              6. Governing Law
            </h2>
            <p>
              These terms are governed by the laws of India. Any disputes shall be subject 
              to the exclusive jurisdiction of the courts in [Your City], India.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}