export default function TermsOfService() {
  const lastUpdated = "January 22, 2026";

  return (
    <div className="min-h-screen bg-white text-zinc-600 py-20 px-6 font-sans">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-5xl font-black text-zinc-900 italic uppercase tracking-tighter mb-4">
          Terms of Service
        </h1>
        <p className="text-zinc-500 text-sm mb-16 font-medium border-b border-zinc-200 pb-8">
          Last Updated: {lastUpdated}
        </p>

        <div className="space-y-16">
          {/* Section 1 */}
          <section>
            <h2 className="text-xl font-bold text-zinc-900 uppercase tracking-widest mb-6 border-l-4 border-red-600 pl-4">
              1. Acceptance of Terms
            </h2>
            <p className="text-lg leading-relaxed">
              By accessing BossWrite (&quot;the Service&quot;), you agree to be bound by these Terms. 
              If you are using the Service on behalf of a business, that business accepts these terms. 
              The Service is operated by [Your Registered Business Name], India.
            </p>
          </section>

          {/* Section 2 */}
          <section>
            <h2 className="text-xl font-bold text-zinc-900 uppercase tracking-widest mb-6 border-l-4 border-red-600 pl-4">
              2. Service Description & AI Credits
            </h2>
            <div className="space-y-4">
              <p className="text-lg leading-relaxed">
                BossWrite provides AI-powered content generation using YouTube transcripts. 
                Access to features is governed by a &quot;Credits&quot; system. 
              </p>
              <ul className="list-disc ml-6 space-y-3 marker:text-red-600 text-zinc-700">
                <li>Credits are consumed upon successful transcription and post generation.</li>
                <li>Credits have no monetary value and are non-transferable.</li>
                <li>We reserve the right to limit video duration (currently 45 minutes) to ensure service stability.</li>
              </ul>
            </div>
          </section>

          {/* Section 3 */}
          <section>
            <h2 className="text-xl font-bold text-zinc-900 uppercase tracking-widest mb-6 border-l-4 border-red-600 pl-4">
              3. YouTube & Third-Party Content
            </h2>
            <div className="space-y-4">
              <p className="text-lg leading-relaxed">Our Service utilizes publicly available YouTube data. You agree that:</p>
              <ul className="list-disc ml-6 space-y-3 marker:text-red-600 text-zinc-700">
                <li>You will only use the Service for videos you have the right to access.</li>
                <li>You will comply with YouTube&apos;s Terms of Service.</li>
                <li>BossWrite is not affiliated with or endorsed by YouTube or Google.</li>
              </ul>
            </div>
          </section>

          {/* Section 4 */}
          <section>
            <h2 className="text-xl font-bold text-zinc-900 uppercase tracking-widest mb-6 border-l-4 border-red-600 pl-4">
              4. User Content & AI Output
            </h2>
            <div className="bg-zinc-50 border border-zinc-200 p-6 rounded-xl">
              <p className="leading-relaxed text-zinc-800">
                You own the &quot;Manifestos&quot; generated by our AI. However, due to the nature of machine learning, 
                outputs may not be unique across users. You are responsible for reviewing and 
                fact-checking any content before publishing it to social media.
              </p>
            </div>
          </section>

          {/* Section 5 */}
          <section>
            <h2 className="text-xl font-bold text-zinc-900 uppercase tracking-widest mb-6 border-l-4 border-red-600 pl-4">
              5. Payments & Refunds
            </h2>
            <p className="text-lg leading-relaxed">
              Payments are processed via Cashfree/Stripe. By purchasing credits, you agree to their 
              respective terms. As per our <a href="/refund" className="text-red-600 font-bold hover:underline">Refund Policy</a>, digital credits are 
              non-refundable once consumed or assigned to your account.
            </p>
          </section>

          {/* Section 6 */}
          <section>
            <h2 className="text-xl font-bold text-zinc-900 uppercase tracking-widest mb-6 border-l-4 border-red-600 pl-4">
              6. Governing Law
            </h2>
            <p className="text-lg leading-relaxed">
              These terms are governed by the laws of India. Any disputes shall be subject 
              to the exclusive jurisdiction of the courts in Jaipur, India.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}